### ISSUE TITLE
Text is not pasted from vim-anywhere

### ISSUE THREAD

**Issue by slonka** [cknadler/vim-anywhere#58] opened 2016-01-25 12:25 UTC
A picture paints a thousand words:

http://recordit.co/hzl3odnRM7

Macbook pro late 2015. Vanilla macvim (homebrew - macvim 7.4-86).

**Comment by cknadler** [comment] 2016-01-28 07:32
Yeah, this is by design. From the readme:

"Once invoked, vim-anywhere will open a buffer. Close it and it's contents are copied to
your **clipboard** and your previous application is refocused."

It just copies the output to your keyboard. There are threads about having it optionally automatically paste, but that likely won't be the default behavior.

Resolving. Feel free to open another issue if you find anything broken.

**Closed by cknadler** 2016-01-28 07:32 UTC
